[package]
name = "xotp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.7"
hmac = "0.11.0"
data-encoding = "2.3.2"